# Used when running locally for ad-hoc testing
services:
  redis:
    ports:
      - ${REDIS_EXPOSE:-127.0.0.1:6379}:6379
    volumes:
      - redisdata:/data
    networks:
      - common_net

  mongodb:
    ports:
      - ${MONGODB_EXPOSE:-127.0.0.1:27017}:27017
    volumes:
      - dbdata:/data/db
      - ./import:/import
    networks:
      - common_net

  otel-collector:
    networks:
      - common_net

volumes:
  dbdata:
  redisdata:
  
networks:
  common_net:
    external: true
    name: ${COMMON_NET_NAME}
