services:
  redis:
    volumes:
      - redisdata:/data
    networks:
      - shared_network

  mongodb:
    volumes:
      - dbdata:/data/db
      - import:/import
    networks:
      - shared_network

volumes:
  redisdata:
  dbdata:
  import:
  
networks:
  shared_network:
    name: shared_network
