# This compose file is imported by PO for tests so intentionally has no volume or network definitions
services:
  redis:
    image: redis:7.2-alpine
    restart: ${RESTART_POLICY:-always}
    command: redis-server --save 60 1 --loglevel warning

  mongodb:
    image: mongo:4.4
    restart: ${RESTART_POLICY:-always}
    command: mongod --wiredTigerCacheSizeGB ${MONGODB_CACHE_SIZE}

  otel-collector:
    image: ghcr.io/open-telemetry/opentelemetry-collector-releases/opentelemetry-collector-contrib:0.123.1
    command: [ "--config=/etc/otel-collector-config.yaml" ]
    volumes:
      - ./otel-collector-config.yaml:/etc/otel-collector-config.yaml