# This compose file is imported by PO for tests so intentionally has no volume or network definitions
services:
  redis:
    image: redis:7.2-alpine
    command: redis-server --save 60 1 --loglevel warning

  mongodb:
    image: mongo:4.4
    command: mongod --wiredTigerCacheSizeGB ${MONGODB_CACHE_SIZE}
    ports:
      - "${MONGO_EXPOSE_PORT:-27017}:27017"
