# This compose file is imported by PO for tests so intentionally has no volume or network definitions
services:
  redis:
    image: redis:7.2-alpine
    restart: ${RESTART_POLICY:-always}
    command: redis-server --save 60 1 --loglevel warning

  mongodb:
    image: mongo:4.4
    restart: ${RESTART_POLICY:-always}
    command: mongod --wiredTigerCacheSizeGB ${MONGODB_CACHE_SIZE}

  postgresql:
    image: ${POSTGRES_IMAGE}
    command: postgres -c shared_buffers=${POSTGRES_SHARED_BUFFERS} -c work_mem=${POSTGRES_WORK_MEM} -c listen_addresses='*'
    restart: ${RESTART_POLICY:-always}
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - PGAUTO_REINDEX=no
    shm_size: ${POSTGRES_SHM_SIZE}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 1s
      timeout: 5s
      retries: 25
