# Used when running locally for ad-hoc testing
services:
  redis:
    ports:
      - ${REDIS_EXPOSE:-127.0.0.1:6379}:6379
    volumes:
      - redisdata:/data
    networks:
      - common_net

  mongodb:
    ports:
      - ${MONGODB_EXPOSE:-127.0.0.1:27017}:27017
    volumes:
      - dbdata:/data/db
      - ./import:/import
    networks:
      - common_net

  otel-collector:
    image: jaegertracing/all-in-one:1.68.0
    ports:
      - 127.0.0.1:55679:55679
      - 127.0.0.1:5775:5775/udp
      - 127.0.0.1:6831:6831/udp
      - 127.0.0.1:6832:6832/udp
      - 127.0.0.1:5778:5778
      - 127.0.0.1:16686:16686
      - 127.0.0.1:14250:14250
      - 127.0.0.1:14268:14268
      - 127.0.0.1:14269:14269
      - 127.0.0.1:4317:4317
      - 127.0.0.1:4318:4318
      - 127.0.0.1:9411:9411
    environment:
      - COLLECTOR_OTLP_ENABLED=true
      - COLLECTOR_ZIPKIN_HOST_PORT=:9411
    command:
    networks:
      - common_net

volumes:
  dbdata:
  redisdata:
  
networks:
  common_net:
    external: true
    name: ${COMMON_NET_NAME}
