# Used when running locally for ad-hoc testing
services:
  redis:
    volumes:
      - redisdata:/data
    networks:
      - shared_network

  mongodb:
    volumes:
      - ${MONGODB_DATA_DIR}:/data/db
      - ./import:/import
    networks:
      - shared_network

volumes:
  redisdata:
  
networks:
  shared_network:
    name: shared_network
