# Used when running locally for ad-hoc testing
services:
  redis:
    volumes:
      - redisdata:/data
    networks:
      - common_net

  mongodb:
    volumes:
      - dbdata:/data/db
      - ./import:/import
    networks:
      - common_net

volumes:
  dbdata:
  redisdata:
  
networks:
  common_net:
    external: true
    name: ${COMMON_NET_NAME}
