services:
  redis:
    restart: always
    volumes:
      - redisdata:/data
    networks:
      - common_net

  mongodb:
    restart: always
    ports:
      - 27017:27017
    volumes:
      - dbdata:/data/db
      - ./import:/import
    networks:
      - common_net

  mongodb_exporter:
    image: bitnami/mongodb-exporter:0
    command: --discovering-mode --mongodb.uri=mongodb://mongodb:27017/admin?ssl=true
    ports:
      - 9216:9216
    networks:
      - common_net

  postgresql:
    ports:
      - 5432:5432
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - common_net

volumes:
  redisdata:
    external: true
    # Use this docker volume name to keep consistency with previous po owned deployment
    name: po_redisdata

  dbdata:
    external: true
    # Use this docker volume name to keep consistency with previous po owned deployment
    name: dbdata

  pg_data:
    external: true
    name: off_shared_pg_data

networks:
  common_net:
    external: true
    name: ${COMMON_NET_NAME}