services:
  redis:
    restart: always
    volumes:
      - redisdata:/data
    networks:
      - common_net

  mongodb:
    restart: always
    ports:
      - 27017:27017
    volumes:
      # Use dbdata docker volume for now to keep consistency with previous po owned deployment
      - dbdata:/data/db
      - ./import:/import
    networks:
      - common_net

  mongodb_exporter:
    image: bitnami/mongodb-exporter:0
    command: --discovering-mode --mongodb.uri=mongodb://mongodb:27017/admin?ssl=true
    ports:
      - 9216:9216
    networks:
      - common_net

  postgresql:
    image: ${POSTGRES_IMAGE}
    command: postgres -c shared_buffers=${POSTGRES_SHARED_BUFFERS} -c work_mem=${POSTGRES_WORK_MEM} -c listen_addresses='*'
    restart: ${RESTART_POLICY:-always}
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - PGAUTO_REINDEX=no
    shm_size: ${POSTGRES_SHM_SIZE}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 1s
      timeout: 5s
      retries: 25
    ports:
      - "${POSTGRES_EXPOSE:-127.0.0.1:5432}:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - common_net

volumes:
  redisdata:
    external: true
    name: ${COMPOSE_PROJECT_NAME}_redisdata

  dbdata:
    external: true
    name: ${MONGODB_DATA_VOLUME}

  pg_data:
    external: true
    name: off_shared_pg_data

networks:
  common_net:
    external: true
    name: ${COMMON_NET_NAME}